TRsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from TRsite import settings 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += [ 
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

goods/urls.py
from django.urls import path
from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('catalog/', views.catalog, name='catalog'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table: str = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name 


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')


    class Meta:
        db_table: str = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты' 
        ordering = ("id",)    

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'   

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100, 2)

        return self.price      
 

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')


    class Meta:
        db_table: str = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователя'

    def __str__(self):
        return self.username 

users/forms.py
from django import forms 
from django.contrib.auth.forms import AuthenticationForm

from users.models import User



class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()

    # username = forms.CharField(
    #     label = 'Имя',
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'form-control',
    #                                   'placeholder': 'Введите ваше имя пользователя'})
    # )
    # password = forms.CharField(
    #     label = 'Пароль',
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                      'class': 'form-control',
    #                                      'placeholder': 'Введите ваш пароль'})
    # )
    class Meta:
        model = User
        fields = ['username', 'password']

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_list_or_404, get_object_or_404, render

from goods.models import Products
from goods.utils import q_search


def catalog(request, category_slug=None):

    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)
    
    if category_slug == "allcoffee":
        goods = Products.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = get_list_or_404(Products.objects.filter(category__slug=category_slug))

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))

    context = {
        "title": "coffee - Каталог",
        "goods": current_page,
        "slug_url": category_slug
    }
    return render(request, "goods/catalog.html", context)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    context = {"product": product}

    return render(request, "goods/product.html", context=context)

main/views.py
from django.http import HttpResponse
from django.shortcuts import render

from goods.models import Categories


def index(request):

    
    context: dict = {
        'title': 'Coffee - Главная',
        'content': "Site-TasteBucks",
    }

    return render(request, 'main/index.html', context)


def about(request):
    context: dict = {
        'title': 'Coffee - О нас',
        'content': "Мы",
        'text_on_page': "Мы очень старались над его созданием."

    }

    return render(request, 'main/about.html', context)

users/views.py
from django.contrib import auth
from django.shortcuts import render

from users.forms import UserLoginForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Coffee - Авторизация',
        'form': form 
    }
    return render(request, 'users/login.html', context)


def registration(request):
    context = {
        'title': 'Coffee - Регистрация'
    }
    return render(request, 'users/registration.html', context)


def profile(request):
    context = {
        'title': 'Coffee - Кабинет'
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    ...


   

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block content %}
<div class="row">
    <!-- Форма фильтров -->
    <div class="dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q %}{% url 'catalog:search' %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexRadioDefault1"></label>
                    кофе по акции
                </label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" 
                {% if request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"  
                {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"  
                {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>
   
    {% if request.GET.q %}
    <h3 class="mt-4">Результаты поиска по запросу {{ request.GET.q }}</h3>
    {% if not goods %}
        <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
        <h2 class="mt-4">По запросу ничего не найдено</h2>
    {% endif %}
    {% endif %}
    {% for product in goods %}
    <!-- Карта товара -->
    <div class="col-lg-4 col-md-6 p-4">
        <div class="card border-primary rounded custom-shadow">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
            {% else %}
                <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
            {% endif %}
            <div class="card-body">
                <a href="{% url "catalog:product" product.slug %}">
                    <p class="card-title">
                        {% autoescape off %}
                            {% if product.headline%}
                            {{product.headline}}
                            {% else %}
                            {{ product.name }}
                            {% endif %}
                        {% endautoescape %}   
                    </p>
                </a>
                <p class="card-text">
                    {% autoescape off %}
                        {% if product.bodyline%}
                        {{product.bodyline|truncatechars:100}}
                        {% else %}
                        {{ product.description|truncatechars:40 }}
                        {% endif %}
                    {% endautoescape %} 
                </p>
                <p class="product_id">id: {{ product.display_id }}</p>
                <div class="d-flex justify-content-between">
                    
                    {% if product.discount %}
                        <p><s>{{product.price}}</s> тг</p>
                        <p><strong>{{ product.sell_price }} тг</strong></p>
                        <span class="badge bg-warning text-dark">{{ product.discount }} %</span>
                    {% else %}
                        <p><strong>{{ product.price }}</strong></p>
                    {% endif %}

                    <a href="#" class="btn add-to-cart">
                        <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                            width="32" height="32">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %} 
    
    
   

</div>
<!-- Пагинация -->
{% if goods %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">

            <li class="page-item {% if not goods.has_previous %}disabled{% endif %}">
              <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}{% else %}#{% endif %}">Назад</a>
            </li>

             {% for page in goods.paginator.page_range %}
             {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
                <li class="page-item {% if goods.number == page %}active{% endif %}">
                    <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                </li>
            {% endif %}
            {% endfor %}

            <li class="page-item {% if not goods.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if goods.has_next %}?{% change_params page=goods.next_page_number %}{% else %}#{% endif %}">Следующая</a>
              </li>
        </div>
    </ul>
</nav>
{% endif %}
{% endblock %}


{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Girlsprogramm</p>
    </div>
</footer>
{% endblock %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card mb-4 custom-shadow">
        <div class="row">
            <!-- Миниатюры -->
            <div class="col-md-4">
                <img src="{{ product.image.url }}"
                    class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
            </div>
            <div class="col-md-4 ">
                <p class="product_id mt-3">id: {{ product.display_id }}</p>
            </div>
            <!-- Увеличить изображение в модальном окне -->
            <div class="modal fade" id="imageModal1" tabindex="-1"
                aria-labelledby="imageModal1Label" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Закрыть"></button>
                        </div>
                        <div class="modal-body">
                            <img src="{{ product.image.url }}"
                                class="img-fluid" alt="Изображение 1">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Описание товара -->
        <div class="card-body">
            <p class="card-text">Цена: <strong>{{ product.sell_price }}тг</strong></p>
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
            <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
        </div>
    </div>
</div>
{% endblock %}

main/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock %}


{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow">
        <h2 class="m-2"><strong>{{ content }}</strong></h2>
        <p class="m-2">{{ text_on_page }}</p>
    </div>
{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Tamilla&Rakhmina</p>
    </div>
</footer>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock %}


{% block content %}
    <h1 class="mt-5 pt-5"><strong>{{ content }}</strong></h1>
{% endblock %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Tamilla&Rakhmina</p>
    </div>
</footer>
{% endblock %}

templates/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}

    {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "user:login" %}">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16" height="16">

                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{category.name}}</a></li>
                        {% endfor %}
                        
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> кофеек на сумму</p>
                                            <h4 class="float-left"><strong>3800 тг</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </section>
    
    {% block footer %}{% endblock %}

    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                    <p>{{form.non_field_errors}}</p>
                    {% endif %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" name="username" id="id_username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите ваш пароль" required>
                    </div> 




                    <!-- {% for item in form %}
                    <div class="mb-3">
                        <label for="{{ item.id_for_label }}" class="form-label">{{ item.label }}</label>
                        {{item}}
                    </div>
                    {% endfor %} -->


                    <!-- <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="mb-3">
                            <label for="password" class="form-label">Пароль</label>
                            {{ form password }}
                        </div> -->
                   
                    <!-- <div class="mb-3">
                        <label for="username" class="form-label">Имя пользователя</label>
                        <input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
                    </div> -->
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration" %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}